# Generated by Django 2.2 on 2021-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20210606_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
