# Generated by Django 2.2 on 2021-06-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_addamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount_to_add',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='AddAmount',
        ),
    ]
