# Generated by Django 2.2 on 2021-06-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20210607_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount_to_add',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
