# Generated by Django 2.2 on 2021-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20210607_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
