# Generated by Django 2.2 on 2021-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_ingredient_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='update_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
