# Generated by Django 2.2 on 2021-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_auto_20210607_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='update_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
