# Generated by Django 2.2 on 2021-06-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20210607_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='total_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('KG', 'kilograms'), ('L', 'liters'), ('PSC', 'pieces')], max_length=3),
        ),
    ]
